- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: lustre
    persistentVolumeClaim:
      claimName: lustre-pvc-vllm
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: lustre
    mountPath: /mnt/lustre
