apiVersion: batch/v1
kind: Job
metadata:
  name: nyann-poker
spec:
  template:
    spec:
      containers:
        - name: nyann-poker
          volumeMounts:
            - name: lustre
              mountPath: /mnt/lustre
      volumes:
        - name: lustre
          persistentVolumeClaim:
            claimName: lustre-pvc-vllm
